<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Spandana-PC" ignored="0" name="TestingFailedTestCases" tests="9" failures="2" timestamp="10 Jan 2019 15:14:14 GMT" time="0.114" errors="0">
  <testcase name="test1" time="0.016" classname="testNG.listeners.RetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.003" classname="testNG.listeners.RetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="testNG.listeners.RetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="testNG.listeners.RetryTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNG.listeners.RetryTest.test1(RetryTest.java:12)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.003" classname="testNG.listeners.RetryTest"/>
  <testcase name="test3" time="0.002" classname="testNG.listeners.RetryTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.002" classname="testNG.listeners.RetryTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.002" classname="testNG.listeners.RetryTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.002" classname="testNG.listeners.RetryTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNG.listeners.RetryTest.test3(RetryTest.java:24)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- TestingFailedTestCases -->
